import React from "react";
import { Link } from "react-router-dom";

const greenHydrogenImage =
  "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=1200&q=80"; // Replace with your actual image

const GreenHydrogen = () => {
  return (
    <div className="relative">
      {/* Main Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 flex flex-col gap-8">
        {/* Top Section */}
        <div className="bg-white shadow-lg rounded-xl border p-6 flex items-center gap-6">
          <div className="flex-1">
            <h1 className="text-4xl font-bold text-gray-900 mb-2">
              Green Hydrogen: A Catalyst for Clean Energy
            </h1>
            <p className="text-lg text-gray-700">
              Green hydrogen is gaining momentum as countries push toward carbon neutrality and energy independence. Here's how it's shaping our clean energy future.
            </p>
          </div>
          <div className="flex-shrink-0 w-1/3">
            <img
              src={greenHydrogenImage}
              alt="Green Hydrogen"
              className="w-full h-auto object-cover rounded-lg shadow-md"
            />
          </div>
        </div>

        {/* Main Content */}
        <div className="space-y-8">
          <section className="prose text-gray-800 text-lg space-y-6">
            <h2 className="font-bold">Market Overview</h2>
            <p>
              Green hydrogen, generated by splitting water through electrolysis powered by renewable sources such as wind, solar, and hydropower, is becoming a key pillar in the worldwide move towards clean energy. In contrast to grey hydrogen, which is produced from natural gas and emits large amounts of CO2, green hydrogen is nearly free of emissions. This makes it an essential tool in reducing global greenhouse gases and tackling climate change. Alongside green hydrogen, e-fuels—also created using renewable electricity—are crucial in driving the green transition, playing a major role in decarbonising industries and transportation around the world.
            </p>
            <p>
              As global demand for cleaner alternatives grows, green hydrogen offers a scalable and versatile solution for energy storage, heavy industry, and long-haul transport. It enables countries to reduce dependency on fossil fuels while enhancing energy security. Furthermore, advancements in electrolyser technologies and supportive government policies are accelerating the commercial adoption of green hydrogen across sectors. Together, green hydrogen and e-fuels are setting the foundation for a more resilient and sustainable energy future.
            </p>
            <p>
              According to a recently published report by Fact Vault Insights, the global green hydrogen market is projected to exceed $64 billion by 2030. Driven by decarbonization efforts, government incentives, and advancements in electrolysis technology, the market is expected to grow at a strong compound annual growth rate (CAGR) of over 41% between 2024 and 2030.
            </p>

            <h3  className="font-bold">Top Leading Companies in the Green Hydrogen Market:</h3>
            <ul className="list-disc pl-5">
              <li>Air Liquide</li>
              <li>Air Products Inc.</li>
              <li>Bloom Energy</li>
              <li>Cummins Inc.</li>
              <li>Engie</li>
              <li>Linde plc</li>
              <li>Nel ASA</li>
              <li>Siemens Energy</li>
              <li>Toshiba Energy Systems & Solutions Corporation</li>
              <li>Uniper SE.</li>
            </ul>

            <h3 className="font-bold" >Market Segmentation</h3>
            <p><strong>By Electrolyzer:</strong> Proton Exchange Membrane Electrolyzer, Alkaline Electrolyzer, Solid Oxide Electrolyzer, Others</p>
            <p><strong>By Source:</strong> Solar Energy, Wind Energy, Others (hydropower, geothermal, and hybrid of solar & wind)</p>
            <p><strong>By End User:</strong> Refining, Ammonia, Methanol, Iron & Steel, Others</p>
            <p><strong>By Geography:</strong> North America, U.S., Canada, Europe, U.K., Germany, France, Asia-Pacific, China, India, Japan, South Korea, Rest of the World</p>

            <h3  className="font-bold" >Market Drivers</h3>
            <ul className="list-disc pl-5">
              <li><strong>Decarbonization Targets:</strong> Global efforts to cut carbon emissions are fueling the rising demand for green hydrogen.</li>
              <li><strong>Technological Progress:</strong> Advancements in electrolyser efficiency and declining production costs are enhancing the competitiveness of green hydrogen.</li>
              <li><strong>Government Incentives:</strong> Supportive policies, subsidies, and funding initiatives are boosting investments in green hydrogen infrastructure.</li>
            </ul>

            <h3>Market Challenges</h3>
            <ul className="list-disc pl-5">
              <li><strong>High Production Costs:</strong> Green hydrogen remains costlier to produce compared to grey hydrogen.</li>
              <li><strong>Infrastructure Gaps:</strong> The limited availability of hydrogen infrastructure is a key barrier to wider adoption.</li>
              <li><strong>Energy Efficiency Concerns:</strong> Ongoing research and development aim to improve the performance of electrolysers and fuel cells.</li>
            </ul>

            <h3  className="font-bold" >Market Trends</h3>
            <ul className="list-disc pl-5">
              <li><strong>Rise of Green Ammonia:</strong> Green hydrogen is increasingly being used to produce green ammonia, offering a low-carbon solution for agriculture and a potential fuel for shipping and power generation.</li>
              <li><strong>Expansion of Hydrogen Fuel Cells:</strong> Hydrogen fuel cells are gaining momentum, particularly in heavy-duty transport.</li>
              <li><strong>Sector Coupling Across Industries:</strong> Green hydrogen is enabling sector coupling by linking the power, industrial, and transportation sectors.</li>
              <li><strong>Scaling Up Production Projects:</strong> Large-scale green hydrogen projects are being announced worldwide, with investments flowing into gigawatt-scale plants.</li>
              <li><strong>Strategic Partnerships and Alliances:</strong> Companies are forming joint ventures and collaborations to pool resources and accelerate infrastructure development.</li>
            </ul>

            <h3  className="font-bold" >Strategic Insights</h3>
            <p>
              To seize opportunities in the rapidly growing green hydrogen market, companies must prioritize scaling up production and investing in cutting-edge electrolyser technologies to drive down costs and enhance efficiency. Building robust infrastructure for hydrogen storage, transport, and distribution is critical for enabling widespread adoption. Strategic collaborations across industries will foster innovation, mitigate risks, and create integrated solutions. Additionally, leveraging government incentives and policies will be essential to accelerate market growth.
            </p>
          </section>
        </div>
      </div>

      {/* Fixed CTA Button */}
      <Link
        to="/contact"
        className="fixed bottom-8 right-8 bg-gradient-to-r from-blue-600 to-blue-800 hover:from-blue-700 hover:to-blue-900 text-white font-medium py-3 px-6 rounded-lg shadow-md hover:shadow-lg transition-all duration-200 transform hover:-translate-y-1"
      >
        Contact to Purchase
      </Link>
    </div>
  );
};

export default GreenHydrogen;
